# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZohoSignSDK-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZohoSignSDK-Example
  pod 'ZohoSignSDK', '~> 1.0.3-Beta'
#pod 'ZohoSignSDK', :git => 'https://github.com/zoho/ZohoSignSDK-iOS.git'

end


post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
    end
end
