# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ZohoSignSDK-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZohoSignSDK-Example
  pod 'ZohoSignSDK', '1.0'
#  pod 'SSZipArchive'
#  pod 'AMPopTip'
##  pod 'MenuItemKit'
#  pod 'Alamofire'
#  pod 'SVProgressHUD'
#  pod 'SnapKit'
#pod 'ZohoSignSDK', :git => 'https://github.com/zoho/ZohoSignSDK-iOS.git'

end


post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end
